### ISSUE TITLE
Criar JS da página de Objeto

### ISSUE THREAD

**Issue by matiasemily** [VitorPandini/14Bits#33]
**Ideias de JS para o site:**
- [x] Menu suspenso no Sudeste

**Revisões pontuadas pela Carol:**
- [x] Criar páginas com conteúdo para os outros estados/cards na página de Estado, mesmo que seja só com aviso de "em construção"
- [x] Fixar os footers na parte debaixo da tela

**Comment by adler-neto** [comment]
Inclui o nav via innerHTML;

manipulação de estilização de imagem adicionando o borderRadius;

manipulação de estilização de texto utilizando o textDecoratione fontWeight para todos os links.

**Comment by matiasemily** [comment]
- Usar animação na imagem do Gustavo Guanabara
- Mover o nav pra estrutura da página (pelo HTML)
- Cursor com JS

**Comment by adler-neto** [comment]
- Manipulação de estilização de imagem adicionando o borderRadius;
- Manipulação de estilização de texto utilizando o textDecoratione fontWeight para todos os links.
- Adicionado um efeito na imagem ao passar o mouse
- Efeito no nav alterando de cor via javaScript
